"""OceanGuard AI — unified FastAPI application.

Mounts all eight pipeline features behind one app, plus investigator
authentication and the public false-positive appeals intake:

    F1 AI Oil-Spill Detection & Look-Alike Analysis
    F2 Multi-Temporal Spill Reconstruction & Characterization
    F3 Environmental Drift & Backward Hindcasting -> Source Hypotheses
    F4 Historical AIS Vessel Reconstruction & Correlation
    F5 Cross-Source Consistency & Evidence Conflict Detection
    F6 Evidence Fusion & Dynamic Hypothesis Ranking
    F7 Forensic Investigation Graph & Explainable Evidence Chain
    F8 Forward Forecasting, Impact Assessment & Historical Replay
    Auth (register/login/roles) and Appeals (public dispute intake + review queue)

Every F1-F8 route requires a signed-in investigator (``Depends(get_current_user)``
attached where each router group is mounted, not inside the router files
themselves, so unit tests that build their own minimal app around one router
are unaffected). ``POST /appeals`` is the one deliberately public route.

Run with: ``uvicorn backend.app:app --reload``
"""
from __future__ import annotations

from pathlib import Path

from fastapi import Depends, FastAPI
from fastapi.middleware.cors import CORSMiddleware
from fastapi.staticfiles import StaticFiles

from backend.appeals.router import router as appeals_router
from backend.auth.dependencies import get_current_user
from backend.auth.router import router as auth_router
from backend.f1_detection.router import router as f1_router
from backend.f2_temporal.router import router as f2_router
from backend.f3_hindcast.router import router as f3_router
from backend.f4_ais.router import router as f4_router
from backend.f5_consistency.router import router as f5_router
from backend.f6_ranking.router import router as f6_router
from backend.f7_graph.router import router as f7_router
from backend.f8_forecast.router import router as f8_router
from backend.reports.router import router as reports_router
from backend.shared.config.settings import settings as f1f2_settings
from shared.config.settings import get_settings

app = FastAPI(
    title="OceanGuard AI — Unified Investigation API",
    version="1.1.0",
    description=(
        "AI-assisted satellite oil-spill investigation and decision-support system: "
        "detection, temporal reconstruction, backward/forward drift modelling, "
        "historical AIS correlation, cross-source consistency, evidence-fusion "
        "ranking, a forensic evidence graph, and forecast/impact/replay - behind "
        "one authenticated API, plus a public false-positive appeals intake. "
        "Reports probable/possible source hypotheses and candidate-vessel "
        "associations, never legal responsibility (see PDF section 11)."
    ),
    docs_url="/docs",
    redoc_url="/redoc",
)

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

_investigator = [Depends(get_current_user)]

# F1/F2 historically dual-mount at both the bare path and an /api/v1 prefix.
app.include_router(f1_router, prefix=f1f2_settings.api_prefix, dependencies=_investigator)
app.include_router(f1_router, dependencies=_investigator)
app.include_router(f2_router, prefix=f1f2_settings.api_prefix, dependencies=_investigator)
app.include_router(f2_router, dependencies=_investigator)

app.include_router(f3_router, dependencies=_investigator)
app.include_router(f4_router, dependencies=_investigator)
app.include_router(f5_router, dependencies=_investigator)
app.include_router(f6_router, dependencies=_investigator)
app.include_router(f7_router, dependencies=_investigator)
app.include_router(f8_router, dependencies=_investigator)

# reports_router enforces auth itself (it needs the resolved user for the
# "generated by" byline), so it isn't in the _investigator group above.
app.include_router(reports_router)

# Auth is unauthenticated by construction (you need it to *get* a token) and
# appeals is deliberately public (see backend/appeals/router.py) except its
# review-queue endpoints, which require_role() protects internally.
app.include_router(auth_router)
app.include_router(appeals_router)

# Satellite quicklook / mask imagery — served as plain static files (public,
# same reasoning as appeals: an appellant contesting a detection may need to
# see the same quicklook an investigator sees, without an account).
_dataset_dir = Path(get_settings().RAW_SYNTHETIC_DIR)
if _dataset_dir.exists():
    app.mount("/media", StaticFiles(directory=str(_dataset_dir)), name="media")


@app.get("/health", tags=["Health"])
def health():
    return {
        "status": "ok",
        "service": "oceanguard-ai",
        "features": ["F1", "F2", "F3", "F4", "F5", "F6", "F7", "F8"],
    }


@app.get("/", tags=["Health"])
def root():
    return {
        "message": "OceanGuard AI — Unified Investigation API",
        "docs": "/docs",
        "health": "/health",
        "auth": ["POST /auth/register", "POST /auth/login", "GET /auth/me"],
        "appeals": ["POST /appeals (public)", "GET /appeals (investigator+)"],
        "pipeline": [
            "POST /api/v1/f1/detect",
            "POST /api/v1/f2/reconstruct/{event_id}",
            "POST /api/v1/f3/hindcast/{event_id}",
            "POST /api/v1/f4/reconstruct-ais/{event_id}",
            "POST /f5/evaluate-consistency/{event_id}",
            "POST /f6/rank/{event_id}",
            "GET  /events/{event_id}/graph",
            "POST /api/v1/f8/forecast/{event_id}",
            "POST /api/v1/f8/replay/{event_id}",
        ],
        "reports": "GET /api/v1/reports/{event_id}/vessels.pdf (investigator+)",
        "media": "GET /media/quicklook/{scene_id}.png",
    }
