"""Builds the per-event "candidate vessel" PDF report.

Reuses the exact same data the dashboard shows - F6's rank_event() for
ranking/explanation and F5's evaluate_consistency() for the supporting/
contradicting evidence behind each candidate - so the PDF and the live
dashboard can never disagree.
"""
from __future__ import annotations

import io
from datetime import datetime, timezone
from typing import Any, Optional

from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import mm
from reportlab.platypus import (
    HRFlowable,
    PageBreak,
    Paragraph,
    SimpleDocTemplate,
    Spacer,
    Table,
    TableStyle,
)

from backend.f5_consistency.service import evaluate_consistency
from backend.f6_ranking.service import rank_event
from backend.f6_ranking.models import RankingResult
from shared.mocks.load_mock import load_mock_df

_BAND_COLOR = {"high": colors.HexColor("#c0392b"), "medium": colors.HexColor("#d68910"), "low": colors.HexColor("#7f8c8d")}
_RELATION_HEX = {"SUPPORTS": "#1e8449", "CONTRADICTS": "#c0392b", "UNKNOWN": "#7f8c8d"}


def _styles():
    ss = getSampleStyleSheet()
    ss.add(ParagraphStyle("ReportTitle", parent=ss["Title"], fontSize=18, spaceAfter=2))
    ss.add(ParagraphStyle("ReportSubtitle", parent=ss["Normal"], fontSize=9, textColor=colors.grey, spaceAfter=10))
    ss.add(ParagraphStyle("SectionHeading", parent=ss["Heading2"], fontSize=13, spaceBefore=14, spaceAfter=6))
    ss.add(ParagraphStyle("VesselHeading", parent=ss["Heading3"], fontSize=12, spaceBefore=10, spaceAfter=4))
    ss.add(ParagraphStyle("Body", parent=ss["Normal"], fontSize=9.5, leading=13))
    ss.add(ParagraphStyle("Small", parent=ss["Normal"], fontSize=8, textColor=colors.grey, leading=11))
    ss.add(ParagraphStyle("Disclaimer", parent=ss["Normal"], fontSize=8.5, leading=12, textColor=colors.HexColor("#7a5b00")))
    ss.add(ParagraphStyle("Mono", parent=ss["Normal"], fontName="Courier", fontSize=8, leading=11, textColor=colors.HexColor("#333333")))
    return ss


def _safe(v: Any, fmt: Optional[str] = None, default: str = "-") -> str:
    if v is None:
        return default
    if fmt:
        try:
            return format(v, fmt)
        except (ValueError, TypeError):
            return str(v)
    return str(v)


def _spill_summary_row(event_id: str) -> dict[str, Any]:
    df = load_mock_df("temporal_states", event_id)
    observed = df[df["state_type"] == "OBSERVED"] if not df.empty and "state_type" in df.columns else df
    if observed.empty:
        return {"count": 0}
    latest = observed.sort_values("timestamp").iloc[-1]
    return {
        "count": len(observed),
        "latest_area_km2": float(latest.get("area_km2", float("nan"))),
        "latest_timestamp": str(latest.get("timestamp", "")),
        "f1_confidence": latest.get("f1_confidence"),
    }


def _source_hypothesis_row(event_id: str) -> Optional[dict[str, Any]]:
    df = load_mock_df("f3", event_id)  # auto-filtered to HBEST for a specific event_id
    if df.empty:
        return None
    row = df.iloc[0]
    return {
        "source_hypothesis_id": row.get("source_hypothesis_id"),
        "lat": row.get("source_lat"),
        "lon": row.get("source_lon"),
        "uncertainty_radius_km": row.get("uncertainty_radius_km"),
        "origin_time_start": row.get("origin_time_start"),
        "origin_time_end": row.get("origin_time_end"),
    }


def _vessel_evidence(relations: list, mmsi: str) -> list:
    """Same matching rule as the dashboard's SidePanel: D5 rows key the vessel
    side of an F3<->F4 pair as "<event_id>-<mmsi>"."""
    return [r for r in relations if r.source_b_id.endswith(f"-{mmsi}") or r.source_a_id.endswith(f"-{mmsi}")]


def build_vessel_report_pdf(event_id: str, *, generated_by: Optional[str] = None) -> bytes:
    """Returns the rendered PDF as bytes."""
    ss = _styles()
    ranking: RankingResult = rank_event(event_id)
    try:
        relations = evaluate_consistency(event_id)
    except Exception:
        relations = []
    spill = _spill_summary_row(event_id)
    hyp = _source_hypothesis_row(event_id)

    buf = io.BytesIO()
    doc = SimpleDocTemplate(
        buf, pagesize=A4,
        leftMargin=18 * mm, rightMargin=18 * mm, topMargin=16 * mm, bottomMargin=16 * mm,
        title=f"OceanGuard AI Candidate Vessel Report — {event_id}",
    )
    story: list[Any] = []

    # ---- Header -----------------------------------------------------------
    generated_at = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    story.append(Paragraph(f"Candidate Vessel Investigation Report — {event_id}", ss["ReportTitle"]))
    by = f" · generated by {generated_by}" if generated_by else ""
    story.append(Paragraph(f"OceanGuard AI (F5 Cross-Source Consistency + F6 Evidence Ranking) · {generated_at}{by}", ss["ReportSubtitle"]))
    story.append(Paragraph(
        "Candidate vessels are evidence-based associations produced for investigation support. "
        "They are <b>not</b> confirmed legal responsibility. Backward drift modelling is uncertain, AIS records are "
        "historical positioning evidence (not proof of presence or absence), and model performance depends on "
        "sensor coverage, data quality, and environmental forcing. A human investigator must review every candidate "
        "before any action is taken.",
        ss["Disclaimer"],
    ))
    story.append(HRFlowable(width="100%", color=colors.HexColor("#dddddd"), spaceBefore=6, spaceAfter=10))

    # ---- Spill summary ------------------------------------------------------
    story.append(Paragraph("Spill summary", ss["SectionHeading"]))
    if spill.get("count"):
        conf = spill.get("f1_confidence")
        conf_str = f"{float(conf) * 100:.0f}%" if conf not in (None, "") else "n/a"
        summary_tbl = Table([
            ["Observed satellite passes", str(spill["count"])],
            ["Latest observed area", f"{spill['latest_area_km2']:.1f} km²"],
            ["Latest observation time", spill["latest_timestamp"]],
            ["Detection confidence (latest)", conf_str],
        ], colWidths=[65 * mm, None])
    else:
        summary_tbl = Table([["No observed satellite passes for this event."]], colWidths=[130 * mm])
    summary_tbl.setStyle(_kv_table_style())
    story.append(summary_tbl)

    # ---- Estimated source ---------------------------------------------------
    story.append(Paragraph("Estimated source region (F3 backward hindcast, pooled best estimate)", ss["SectionHeading"]))
    if hyp:
        source_tbl = Table([
            ["Hypothesis ID", _safe(hyp["source_hypothesis_id"])],
            ["Location", f"{_safe(hyp['lat'], '.4f')}, {_safe(hyp['lon'], '.4f')}"],
            ["Uncertainty radius", f"{_safe(hyp['uncertainty_radius_km'], '.1f')} km"],
            ["Plausible origin window", f"{_safe(hyp['origin_time_start'])} — {_safe(hyp['origin_time_end'])}"],
        ], colWidths=[65 * mm, None])
    else:
        source_tbl = Table([["No source hypothesis available for this event."]], colWidths=[130 * mm])
    source_tbl.setStyle(_kv_table_style())
    story.append(source_tbl)

    # ---- Ranking summary table -----------------------------------------------
    story.append(Paragraph("Candidate vessel ranking", ss["SectionHeading"]))
    if ranking.event_insufficient_evidence:
        story.append(Paragraph(
            "<b>Insufficient evidence.</b> The system did not identify a leading candidate with enough "
            "supporting evidence for this event — this is a deliberate outcome, not a failure. See PDF Technical "
            "Boundaries §11 and Features.md F20 (\"correct non-attribution\").",
            ss["Disclaimer"],
        ))
    if ranking.candidates:
        header = ["Rank", "MMSI", "Type", "Score", "Confidence", "Support", "Contra."]
        rows = [header]
        for c in ranking.candidates:
            rows.append([
                str(c.rank), c.candidate_mmsi, _safe(c.vessel_type), f"{c.final_score:.2f}",
                c.confidence_band, str(c.support_count), str(c.contradiction_count),
            ])
        rank_tbl = Table(rows, colWidths=[14 * mm, 26 * mm, 26 * mm, 18 * mm, 24 * mm, 18 * mm, 18 * mm], repeatRows=1)
        style = [
            ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#1b1f2a")),
            ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
            ("FONTSIZE", (0, 0), (-1, -1), 9),
            ("GRID", (0, 0), (-1, -1), 0.4, colors.HexColor("#cccccc")),
            ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, colors.HexColor("#f5f5f7")]),
            ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
            ("TOPPADDING", (0, 0), (-1, -1), 4),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
        ]
        for i, c in enumerate(ranking.candidates, start=1):
            style.append(("TEXTCOLOR", (4, i), (4, i), _BAND_COLOR.get(c.confidence_band, colors.black)))
        rank_tbl.setStyle(TableStyle(style))
        story.append(rank_tbl)
    else:
        story.append(Paragraph("No candidate vessels were compatible with the source window for this event.", ss["Body"]))

    # ---- Per-vessel detail ----------------------------------------------------
    if ranking.candidates:
        story.append(PageBreak())
        story.append(Paragraph("Evidence detail per candidate", ss["SectionHeading"]))
        for c in ranking.candidates:
            story.append(Paragraph(f"Rank {c.rank} — MMSI {c.candidate_mmsi} ({c.confidence_band} confidence)", ss["VesselHeading"]))
            detail_tbl = Table([
                ["Final score", f"{c.final_score:.3f}", "Source probability", f"{c.source_probability:.2f}"],
                ["Vessel type", _safe(c.vessel_type), "Spatial compatibility", f"{c.spatial_compatibility:.2f}"],
                ["Distance to source", f"{_safe(c.distance_to_source_km, '.1f')} km", "Temporal compatibility", f"{c.temporal_compatibility:.2f}"],
                ["AIS dark gap over source", "yes" if c.dark_gap_over_source else "no", "Drift compatibility", f"{c.drift_compatibility:.2f}"],
                ["Margin to next candidate", f"{c.margin_to_next:.3f}", "AIS completeness", f"{c.ais_completeness:.2f}"],
                ["Evidence items considered", str(c.n_evidence_items), "Behavioural score", f"{c.behavioural_score:.2f}"],
            ], colWidths=[42 * mm, 30 * mm, 42 * mm, 22 * mm])
            detail_tbl.setStyle(TableStyle([
                ("FONTSIZE", (0, 0), (-1, -1), 8.5),
                ("TEXTCOLOR", (0, 0), (0, -1), colors.grey),
                ("TEXTCOLOR", (2, 0), (2, -1), colors.grey),
                ("TOPPADDING", (0, 0), (-1, -1), 2),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 2),
            ]))
            story.append(detail_tbl)
            story.append(Spacer(1, 4))
            story.append(Paragraph(f"<i>Why this rank:</i> {c.explanation}", ss["Mono"]))

            ev = _vessel_evidence(relations, c.candidate_mmsi)
            if ev:
                story.append(Spacer(1, 4))
                for r in ev:
                    hexcolor = _RELATION_HEX.get(r.relation, "#000000")
                    story.append(Paragraph(
                        f'<font color="{hexcolor}"><b>{r.relation}</b></font> '
                        f"— {r.source_a_type} ↔ {r.source_b_type}: {r.reason}",
                        ss["Body"],
                    ))
            story.append(HRFlowable(width="100%", color=colors.HexColor("#e5e5e5"), spaceBefore=8, spaceAfter=4))

    story.append(Spacer(1, 10))
    story.append(Paragraph(
        "Generated by OceanGuard AI — an AI-assisted decision-support system, not an automated enforcement or "
        "vessel-accusation system. See the project's Technical Research Specification for full methodology, "
        "literature basis, and validation.",
        ss["Small"],
    ))

    doc.build(story, onFirstPage=_footer, onLaterPages=_footer)
    return buf.getvalue()


def _kv_table_style() -> TableStyle:
    return TableStyle([
        ("FONTSIZE", (0, 0), (-1, -1), 9.5),
        ("TEXTCOLOR", (0, 0), (0, -1), colors.grey),
        ("TOPPADDING", (0, 0), (-1, -1), 3),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 3),
        ("LINEBELOW", (0, 0), (-1, -1), 0.25, colors.HexColor("#eeeeee")),
    ])


def _footer(canvas, doc):
    canvas.saveState()
    canvas.setFont("Helvetica", 7.5)
    canvas.setFillColor(colors.grey)
    canvas.drawString(18 * mm, 10 * mm, "OceanGuard AI — investigation support, not legal attribution")
    canvas.drawRightString(A4[0] - 18 * mm, 10 * mm, f"Page {doc.page}")
    canvas.restoreState()
